version: '0.0.0'
services:
  frontend:
    image: ghcr.io/siberianhusky10/big-event--webcode/vue-app:latest
    container_name: big-event-webcode
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet: