version: '0.0.0'
services:
  frontend:
    image: ghcr.io/siberianhusky10/big-event--webcode/vue-app:latest
    container_name: big-event-webcode
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - webnet

networks:
  webnet: